
<?php
echo $this->headMeta().PHP_EOL;
echo $this->headTitle().PHP_EOL;
echo $this->headLink().PHP_EOL;
echo $this->headScript().PHP_EOL;
?>

<ul class="nav nav-tabs">
    <li class="nouveau"><a href="<?php echo $this->url(array('controller' => 'doctor', 'action' => 'list'), null, true) ?>">Doctor</a></li>
    <li><a href="#">Draft</a></li>
    <li><a href="#">Validate</a></li>
    <li class="#"><a href="#">Add New</a></li>
</ul>

<div class="filter">


    <?php

    echo $this->form ;
    ?>
 </div>



