<p>Are you sure that you want to delete
<?php echo $this->escape($this->doctor['family_name']); ?>

<?php echo $this->escape($this->doctor['name']); ?>?
</p>

<form action="<?php echo $this->url(array('action'=>'delete')); ?>" method="post">
<div>
  <input type="hidden" name="id" value="<?php echo $this->doctor['id']; ?>" />
  <input type="submit" name="del" value="Yes" />
  <input type="submit" name="del" value="No" />
</div>
</form>