<?php
echo $this->headMeta().PHP_EOL;
echo $this->headTitle().PHP_EOL;
echo $this->headLink().PHP_EOL;
echo $this->headScript().PHP_EOL;
?>

<ul class="nav nav-tabs">
    <li class="nouveau"><a href="<?php echo $this->url(array('controller' => 'mother', 'action' => 'list'), null, true) ?>">Mother</a></li>
    <li><a href="#">Draft</a></li>
    <li><a href="#">Validate</a></li>
    <li class="<?php echo $this->url(array('controller' => 'mother', 'action' => 'add'), null, true) ?>"><a href="#">Add New</a></li>
</ul>
